version: '3.8'
services:
  dev:
    container_name: go_opa_reviewer_dev
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
      target: develop
    platform: linux/amd64
    volumes:
      - './:/usr/code'
    working_dir: '/usr/code'
    env_file:
      - .env
    command: [ '/bin/sh', '-c', 'tail -f /dev/null' ]
    restart: always
