AWSTemplateFormatVersion: "2010-09-09"

Description: Go OPA Reviewer GitHub App Secrets.

Parameters:
  GitHubAppSecretArnParamName:
    Description: GitHub App Secret Arn Parameter Name
    Type: String

  GitHubAppSecretIdParamName:
    Description: GitHub App Secret Id Parameter Name
    Type: String

Resources:
  GitHubAppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref AWS::StackName
      Description: GitHub App Secret.

  GitHubAppSecretArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref GitHubAppSecretArnParamName
      Description: GitHub App Secret ARN.
      Type: String
      Value: !Ref GitHubAppSecret

  GitHubAppSecretIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref GitHubAppSecretIdParamName
      Description: GitHub App Secret ID.
      Type: String
      Value: !GetAtt GitHubAppSecret.Id
